apiVersion: v1
kind: Service
metadata:
  name: laravel2
spec:
  type: NodePort
  selector:
    app: laravel2
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30008

# apiVersion: v1
# kind: Service
# metadata:
#   name: laravel-service-2
# spec:
#   # type: LoadBalancer
#   ports:
#     - port: 8000
#       protocol: TCP
#       targetPort: 80
#   selector:
#     app: laravel2